
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 19 23:37:24 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 39;
  public static final int INCREMENT = 31;
  public static final int CHAR = 46;
  public static final int CONST = 6;
  public static final int GREATEROREQUAL = 25;
  public static final int NOTEQUAL = 23;
  public static final int LPAREN = 37;
  public static final int GREATER = 24;
  public static final int SEMI = 33;
  public static final int CONTINUE = 14;
  public static final int LESS = 26;
  public static final int FOR = 15;
  public static final int MINUS = 18;
  public static final int DECREMENT = 32;
  public static final int RPAREN = 38;
  public static final int STATIC = 16;
  public static final int AND = 28;
  public static final int OR = 29;
  public static final int BOOL = 45;
  public static final int COMMA = 35;
  public static final int CLASS = 4;
  public static final int EQUALEQUAL = 22;
  public static final int DIV = 20;
  public static final int LESSOREQUAL = 27;
  public static final int NUM = 47;
  public static final int PLUS = 17;
  public static final int IF = 7;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 40;
  public static final int EQUAL = 30;
  public static final int LAMBDA = 43;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int MOD = 21;
  public static final int IDENT = 44;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int COLON = 34;
  public static final int LBRACE = 41;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int RBRACE = 42;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int PRINT = 9;
}

